#Expyriment 1.0.0 (Python 3.11.9), .xpe-file, coding: cp1252
#date: Fri Sep 19 2025 00:15:26
#sha1: 140c45
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='Madhusree', release='10', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
433,stderr,received,'Exception ignored in: <function Visual.__del__ at 0x000002C3020CE3E0>'
433,stderr,received,'Traceback (most recent call last):'
433,stderr,received,'  File "C:\\Users\\aviba\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\expyriment\\stimuli\\_visual.py", line 266, in __del__'
434,stderr,received,'    if self._compression_filename is not None:'
434,stderr,received,'       ^^^^^^^^^^^^^^^^^^^^^^^^^^'
434,stderr,received,"AttributeError: 'Line' object has no attribute '_compression_filename'"
435,stderr,received,'Traceback (most recent call last):'
435,stderr,received,'  File "C:\\Users\\aviba\\downloads\\cogsup-core1\\programming\\assignments\\week-2\\exercises\\labeled_shapes.py", line 40, in <module>'
435,stderr,received,'    triangle_line = stimuli.Line('
435,stderr,received,'                    ^^^^^^^^^^^^^'
435,stderr,received,"TypeError: Line.__init__() got an unexpected keyword argument 'start'"
